# Generated by Django 6.0 on 2026-01-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_publisher_is_email_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
